### ISSUE TITLE
Some of the issues i've noticed

### ISSUE THREAD

**Issue by Enigma1309** [PROxZIMA/.dotfiles#7]
1. Power button does nothing, have to maually type wlogout in terminal.
2.There's a error in line 100 and 101 in hyprland.conf.
3. when we press windows key and search something, say , Thunar, even if it's installed it won't show in the menu, that's frustrating.
4. My bluetooth icon does not show in the waybar.
5. The wallpaper change icon is quite offset and disordered in shape
6. for kitty the terminal shows quite weird behaviour when we go to thunar and rightclick and open terminal here, the transparency and effects of terminal gets lost.
7. Loved this project a lot please do a fix on the given issues ❤️.
 Thank You

**Comment by PROxZIMA** [comment]
> 1. Power button does nothing, have to maually type wlogout in terminal.

Run `chmod +x` on the script files. On all script files tbh.

> 2. There's a error in line 100 and 101 in hyprland.conf.

I guess that's `col_group` related thing. I haven't yet pushed that lil change according to the new hyprland's release yet. Will do that.

> 2. when we press windows key and search something, say , Thunar, even if it's installed it won't show in the menu, that's frustrating.

Umm maybe that's `wofi` related thing? I've switched to `tofi` as it's quite fast and sleak. But my take is that this issue is not related to my .dotfiles

> 3. My bluetooth icon does not show in the waybar.

Bluetooth icon is managed by `pulseaudio` in waybar's config. So again not related to my dots.

https://github.com/PROxZIMA/.dotfiles/blob/11fe8002ff1018ec7676e4e80670235033a78b7d/.config/waybar/config.jsonc#L143-L164

If you are talking about this bluetooth icon 
![image](https://user-images.githubusercontent.com/43103163/226093414-0928ec0f-902c-4542-9616-1de7aeac8a27.png)
then its `blueman-applet` icon.

> 4. The wallpaper change icon is quite offset and disordered in shape

Ikr, it looks bigger than the others but I've cross checked the css and there's no difference there -_-

Kinda perspective issue. I'll make it a bit smaller so that it somehow resembles the icons and the workspace indicator.


> 5. for kitty the terminal shows quite weird behaviour when we go to thunar and rightclick and open terminal here, the transparency and effects of terminal gets lost.

Are you sure that thunar is opening kitty only? (and not alacrity)

---

Thanks for the love 💜

**Comment by Enigma1309** [comment]
chmod +x didn't worked for me i've figured out that i've to use chown command (_fixed 1_).
uncommenting those line fixed the issues (_fixed 2_).
the issue was with the fuzzy search so i have to change it to false in your dots. (_fixed_).
blueman-applet was not installed so i did it (_fixed 3_).
i am not able to change the css for wallpaper changer since i have a very little knowledge about it ( **NOT fixed 4**).
yeah thunar was opening xfce-terminal for some reasons so i've fixed it in thunar settings(_fixed 5_ ).


well this solved a lot of problems but still some exists like:-

7) cpu temperature does not update and stucks on 17 degree (WTF my room temp is 35 degree 💀).
8) when we logout and login again after a fixed inteerval of time the computer freezes and i had to manually press SUPER , SHIFT, esc ,  but still after log in it gets stuck after few minutes.(and i've confirmed that it's the problem in these dots only).
so i have to hardshutdown the pc.
9) thunar theme is not consistent when opening thunar it shows your theme but after it's been opened by another app, say firefox to upload or download, it shows an old fashioned theme .
10)i've found this bug that when we hold a windows (by SUPER and mouse down) and change the workspace by scrolling (since super key is already pressed) the window bugs out and disappears but still gets tiled along other apps, idk whether this bug is related to your dots or Hyprland itself

**Comment by Enigma1309** [comment]
also for some reasond my kitty shell prompt isn't getting customized as it was in your reddit video

**Comment by Enigma1309** [comment]
also for some reasons my kitty shell prompt isn't getting customized as it was in your reddit video

**Comment by PROxZIMA** [comment]
> 7. cpu temperature does not update and stucks on 17 degree (WTF my room temp is 35 degree skull).

This is again a related to waybar module. 
https://github.com/PROxZIMA/.dotfiles/blob/d0a0b31908f41f1b4522d18439c645ceaa189469/.config/waybar/config.jsonc#L72-L86

> 8. when we logout and login again after a fixed inteerval of time the computer freezes and i had to manually press SUPER , SHIFT, esc ,  but still after log in it gets stuck after few minutes.(and i've confirmed that it's the problem in these dots only). so i have to hardshutdown the pc.

How did you confirm this? You sure that this freeze ain't related to nvidia or hyprland? I didn't come across such issue :(

> 9. thunar theme is not consistent when opening thunar it shows your theme but after it's been opened by another app, say firefox to upload or download, it shows an old fashioned theme .

See this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1535230). Have you properly updated `~/.gtkrk-2.0` and `~/.config/gtk-3.0/settings.ini` with the correct theme name?

> 10. i've found this bug that when we hold a windows (by SUPER and mouse down) and change the workspace by scrolling (since super key is already pressed) the window bugs out and disappears but still gets tiled along other apps, idk whether this bug is related to your dots or Hyprland itself

https://user-images.githubusercontent.com/43103163/226173097-5d7be679-a013-4ea4-9de7-c3e56663e664.mp4

Why is this a bug? hehehehe

> also for some reasons my kitty shell prompt isn't getting customized as it was in your reddit video

I'm using `starship` for the prompt. Also check `~/.zshrc` for starship initialization.

**Comment by Fufuos** [comment]
Hey! Just wanted to drop some solutions on some of the similar problems I faced. Some of the problems here I never had, but some I did. I also want to say that I LOVE your dotfiles, and I hope this helps others who feel the same. There are a few things I found so far missing in your install instructions. I am also a novice in Linux so be wary of following these solutions.

> Power button does nothing, have to manually type wlogout in the terminal.

First, there is a dependency in your wlogout using "yad" to handle your confirmation window. This was missing from the initial install. To fix this:
`Paru -S yad`
Second, you also have to chmod +x two files. `actions` and `launch.sh`. While digging through the config files I found out that they lacked permissions.
`cd ~/.config/wlogout`
`chmod +x actions launch.sh`

This fixes wlogout and the power button.

> Bluetooth

yeah just had to install blueman
`Paru -S blueman`

I also noticed that you are using libinput-gestures and installed that too
`Paru -S libinput-gestures`

> also for some reasons my kitty shell prompt isn't getting customized as it was in your reddit video

For the shell and terminal customization, you just had to change your default shell + terminal and download zsh + oh-my-zsh along with the plugins.

`chsh /usr/bin/zsh`

`some config stuff for starship I don't remember sorry.`

` sudo git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions`

`sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting`

Also a few problems I have yet to solve:
11. your volume doesn't seem to have a limit? It can go past 100% which I'm not sure is your intention or not. 
12. I have yet to fix your weather module in the waybar config. For me, in my fresh install, it doesn't seem to work.
13. Lock screen leaves a "white" background with a vignette instead of a transparent blurring of the desktop.
14. Shutting down takes FOREVER. I've had shutdowns vary from a minute to five from the shutdown tile in wlogout. Not sure what's the holdup on the system. Maybe some service is doing something? Dunno, not very knowledgeable.
15. Brightness control doesn't work. Not sure if it isn't picking up the key input or just straight up unable to read the brightness. But I'm pretty sure it's a problem with the frameworks laptop. There are numerous forum posts online I just haven't gone around to fix it yet...

**Comment by PROxZIMA** [comment]
Thanks for the help. I missed to update the readme while pushing the new changes :p

> some config stuff for starship I don't remember sorry.

Nope, nothing required for starship. The config file will do it.

> your volume doesn't seem to have a limit? It can go past 100% which I'm not sure is your intention or not.

It's waybar's pulseaudio module. You might need to report the issue there.
https://github.com/PROxZIMA/.dotfiles/blob/5074b85c1d9c73b8a86fde17724f0ee31d3177ff/.config/waybar/config.jsonc#L145-L166

> I have yet to fix your weather module in the waybar config. For me, in my fresh install, it doesn't seem to work.

A little update here :p
![Screenshot_2023-04-16_21-41-26](https://user-images.githubusercontent.com/43103163/232325857-f4d53808-7f7f-4401-a456-b15a9c0fe720.png)

> Lock screen leaves a "white" background with a vignette instead of a transparent blurring of the desktop.

https://github.com/mortie/swaylock-effects/issues/97#issuecomment-1373622754

> Shutting down takes FOREVER. I've had shutdowns vary from a minute to five from the shutdown tile in wlogout. Not sure what's the holdup on the system. Maybe some service is doing something? Dunno, not very knowledgeable.

Yes, this thing is concerning me as well. I'm looking into it.

> Brightness control doesn't work. Not sure if it isn't picking up the key input or just straight up unable to read the brightness. But I'm pretty sure it's a problem with the frameworks laptop. There are numerous forum posts online I just haven't gone around to fix it yet...

https://github.com/PROxZIMA/.dotfiles/blob/5074b85c1d9c73b8a86fde17724f0ee31d3177ff/.config/waybar/config.jsonc#L167-L184

Well... https://github.com/haikarainen/light It's abandoned.

**Comment by Enigma1309** [comment]
thanks both of you guys i really appreciate your efforts

**Comment by Fufuos** [comment]
Alright so, came back from tinkering a bit more. 

First, not sure where or how you are accessing the weather module. It doesn't even show up in the waybar. Not sure if there is a package involved since your script pulls weather information from the website in Python (I think). Maybe something is wrong with my waybar configuration? Uncommenting the module and refreshing it shows no changes.

> Lock screen leaves a "white" background with a vignette instead of a transparent blurring of the desktop.

Downloaded `swaylock-effects-git` and resolved my issue. Apparently the `swaylock-effects` package in AUR is still under the old author. It has been forked and is now managed by jirutka in the swaylock-effects-git package. 

> Shutting down takes FOREVER. I've had shutdowns vary from a minute to five from the shutdown tile in wlogout. Not sure what's the holdup on the system. Maybe some service is doing something? Dunno, not very knowledgeable.

Found a solution! Just installed the `sddm-git` version to replace my `sddm` package. 

> Brightness control doesn't work. Not sure if it isn't picking up the key input or just straight up unable to read the brightness. But I'm pretty sure it's a problem with the frameworks laptop. There are numerous forum posts online I just haven't gone around to fix it yet...

Didn't know the package was abandoned... Going to have to switch down the line if it doesn't get adopted or if problems arise. However... I embarrassingly fixed my problem by downloading the light package. I forgot to check if it was even downloaded so now it works. Will stick with it for now xd. Might be missing in your package list, I don't know if it's  a dependency, might have just been me.

**Comment by PROxZIMA** [comment]
Having separate components for clipboard/weather/wallpaper was cluttering waybar. So I wrote a python script which creates an appindicator for those small things (https://github.com/PROxZIMA/.dotfiles/blob/master/.scripts/appindicator.py). Try running the file manually and if there is any error then create a different issue.

Weather data is fetched using the wttr.in api

I think all the issues are fixed here. Right?
